var quantidadeVendedores = 8;
var rua = "Carmelia dos santos n:30"
var precoEtanol = 6.50;
var lampada = true;
var cep = "132412";
var andarElevador = 2;
var luzAndar = true;
var aniversario = "09/03/1999";
var pesoPrato = "5kl";
var numBois = 10;
var datPasc = "09/08/2021";
var caixaLaran = 82;
var vogal = "a"
var livro = "Um conto de fadas";
var cataoLimite = "R$1500,00";
var horaJogo = "7:00"
var tamanhoPredio = "180m"
var paginas = 40;
var salaReuniao = true;
var enunciado = true;